### PR TITLE
Add CSV mock

### PR DESCRIPTION
**Pull request by JanJanda**
This is a basic skeleton for future feature.

### CODE REVIEW

**Comment by jakubklimek** [comment]
@JanJanda I guess we will also need (at least for the time being) a CSV switch in the specification manager?
image

**Comment by skodapetr** [comment]
We may consider other way then manual, for example the UI can be generated from generator metadata.

**Comment by JanJanda** [comment]
We have run into a problem with configuration. There was some duplicit code between specification manager and schema generator. I have fixed it with a temporary hotfix and @sstenchlak is going to perform refactoring to fix it permanently. For this reason the mentioned CSV switch cannot be added at this time. I assume it will be added by me or someone else in the future.

**Comment by sstenchlak** [comment]
That is correct. Unfortunately, there is technical debt waiting to be paid by me.

@jakubklimek that should be my part to implement. The most correct workflow is that @JanJanda implements only the generator itself (located in packages/core/src/csv-schema/) with spec.ts files that test its functionality. Then I do the "rest". The idea is to make strict rules about who is responsible for what. So this PR is mainly about the `@model-driven-data/core` library than the UI and integration to the rest of the app. @JanJanda just wanted to try to integrate the CSV generator by himself I agreed with that. I'll do the rest soon.

**Pull request merged**
